# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: graph_resource_config.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import lm_rescorer_config_pb2 as lm__rescorer__config__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='graph_resource_config.proto',
  package='mobvoi',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1bgraph_resource_config.proto\x12\x06mobvoi\x1a\x18lm_rescorer_config.proto\"\xac\x01\n\x13\x45xpanderCacheConfig\x12)\n\x10state_table_path\x18\x01 \x01(\t:\x0fstate_table.bin\x12\x39\n\x18replace_state_table_path\x18\x02 \x01(\t:\x17replace_state_table.bin\x12/\n\x13\x65xpander_cache_path\x18\x03 \x01(\t:\x12\x65xpander_cache.bin\"\xeb\x01\n\x13GraphResourceConfig\x12\x12\n\nmodel_type\x18\x01 \x01(\t\x12\x18\n\x10transition_model\x18\x02 \x01(\t\x12\r\n\x05graph\x18\x03 \x01(\t\x12\x0f\n\x07hotword\x18\x04 \x01(\t\x12\x34\n\x12lm_rescorer_config\x18\x05 \x01(\x0b\x32\x18.mobvoi.LMRescorerConfig\x12:\n\x15\x65xpander_cache_config\x18\x06 \x01(\x0b\x32\x1b.mobvoi.ExpanderCacheConfig\x12\x14\n\x0crelabel_file\x18\x07 \x01(\t'
  ,
  dependencies=[lm__rescorer__config__pb2.DESCRIPTOR,])




_EXPANDERCACHECONFIG = _descriptor.Descriptor(
  name='ExpanderCacheConfig',
  full_name='mobvoi.ExpanderCacheConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='state_table_path', full_name='mobvoi.ExpanderCacheConfig.state_table_path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=b"state_table.bin".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='replace_state_table_path', full_name='mobvoi.ExpanderCacheConfig.replace_state_table_path', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=b"replace_state_table.bin".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='expander_cache_path', full_name='mobvoi.ExpanderCacheConfig.expander_cache_path', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=b"expander_cache.bin".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=238,
)


_GRAPHRESOURCECONFIG = _descriptor.Descriptor(
  name='GraphResourceConfig',
  full_name='mobvoi.GraphResourceConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='model_type', full_name='mobvoi.GraphResourceConfig.model_type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='transition_model', full_name='mobvoi.GraphResourceConfig.transition_model', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='graph', full_name='mobvoi.GraphResourceConfig.graph', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hotword', full_name='mobvoi.GraphResourceConfig.hotword', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lm_rescorer_config', full_name='mobvoi.GraphResourceConfig.lm_rescorer_config', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='expander_cache_config', full_name='mobvoi.GraphResourceConfig.expander_cache_config', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='relabel_file', full_name='mobvoi.GraphResourceConfig.relabel_file', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=241,
  serialized_end=476,
)

_GRAPHRESOURCECONFIG.fields_by_name['lm_rescorer_config'].message_type = lm__rescorer__config__pb2._LMRESCORERCONFIG
_GRAPHRESOURCECONFIG.fields_by_name['expander_cache_config'].message_type = _EXPANDERCACHECONFIG
DESCRIPTOR.message_types_by_name['ExpanderCacheConfig'] = _EXPANDERCACHECONFIG
DESCRIPTOR.message_types_by_name['GraphResourceConfig'] = _GRAPHRESOURCECONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ExpanderCacheConfig = _reflection.GeneratedProtocolMessageType('ExpanderCacheConfig', (_message.Message,), {
  'DESCRIPTOR' : _EXPANDERCACHECONFIG,
  '__module__' : 'graph_resource_config_pb2'
  # @@protoc_insertion_point(class_scope:mobvoi.ExpanderCacheConfig)
  })
_sym_db.RegisterMessage(ExpanderCacheConfig)

GraphResourceConfig = _reflection.GeneratedProtocolMessageType('GraphResourceConfig', (_message.Message,), {
  'DESCRIPTOR' : _GRAPHRESOURCECONFIG,
  '__module__' : 'graph_resource_config_pb2'
  # @@protoc_insertion_point(class_scope:mobvoi.GraphResourceConfig)
  })
_sym_db.RegisterMessage(GraphResourceConfig)


# @@protoc_insertion_point(module_scope)
