# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lm_rescorer_config.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='lm_rescorer_config.proto',
  package='mobvoi',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18lm_rescorer_config.proto\x12\x06mobvoi\"Q\n\x0bKenLMConfig\x12\x13\n\x0bngram_order\x18\x01 \x02(\x05\x12\x12\n\nmodel_path\x18\x02 \x02(\t\x12\x19\n\x11relabel_file_path\x18\x03 \x02(\t\"\xe0\x01\n\x1c\x43ontextScoringFunctionConfig\x12<\n\x0b\x61pp_context\x18\x01 \x01(\x0b\x32\'.mobvoi.AppContextScoringFunctionConfig\x12@\n\rquery_context\x18\x02 \x01(\x0b\x32).mobvoi.QueryContextScoringFunctionConfig\x12@\n\rclass_context\x18\x03 \x01(\x0b\x32).mobvoi.QueryContextScoringFunctionConfig\"\xcd\x01\n\x1f\x41ppContextScoringFunctionConfig\x12\x1b\n\rlength_linear\x18\x01 \x01(\x08:\x04true\x12\x12\n\x05\x61lpha\x18\x02 \x01(\x02:\x03\x30.9\x12\x0f\n\x04\x62\x65ta\x18\x03 \x01(\x02:\x01\x31\x12\r\n\x02p1\x18\x04 \x01(\x02:\x01\x30\x12\x10\n\x02p2\x18\x05 \x01(\x02:\x04-1.5\x12\x19\n\nfull_match\x18\x06 \x01(\x08:\x05\x66\x61lse\x12\x15\n\nlength_pow\x18\x07 \x01(\x02:\x01\x31\x12\x15\n\nmin_length\x18\x08 \x01(\x05:\x01\x31\"\xcf\x01\n!QueryContextScoringFunctionConfig\x12\x1c\n\rlength_linear\x18\x01 \x01(\x08:\x05\x66\x61lse\x12\x12\n\x05\x61lpha\x18\x02 \x01(\x02:\x03\x30.8\x12\x0f\n\x04\x62\x65ta\x18\x03 \x01(\x02:\x01\x31\x12\x0e\n\x02p1\x18\x04 \x01(\x02:\x02-1\x12\x0e\n\x02p2\x18\x05 \x01(\x02:\x02-2\x12\x19\n\nfull_match\x18\x06 \x01(\x08:\x05\x66\x61lse\x12\x15\n\nlength_pow\x18\x07 \x01(\x02:\x01\x31\x12\x15\n\nmin_length\x18\x08 \x01(\x05:\x01\x31\"+\n\x19\x42\x61seScoringFunctionConfig\x12\x0e\n\x06weight\x18\x01 \x03(\x02\"\xe6\x01\n\x10LMRescorerConfig\x12\x12\n\nmodel_type\x18\x01 \x02(\t\x12)\n\x0ckenlm_config\x18\x02 \x03(\x0b\x32\x13.mobvoi.KenLMConfig\x12\x16\n\x0ehomophone_path\x18\x03 \x01(\t\x12=\n\x0f\x66unction_config\x18\x04 \x01(\x0b\x32$.mobvoi.ContextScoringFunctionConfig\x12<\n\x11\x62\x61se_score_config\x18\x05 \x01(\x0b\x32!.mobvoi.BaseScoringFunctionConfig'
)




_KENLMCONFIG = _descriptor.Descriptor(
  name='KenLMConfig',
  full_name='mobvoi.KenLMConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ngram_order', full_name='mobvoi.KenLMConfig.ngram_order', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='model_path', full_name='mobvoi.KenLMConfig.model_path', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='relabel_file_path', full_name='mobvoi.KenLMConfig.relabel_file_path', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=117,
)


_CONTEXTSCORINGFUNCTIONCONFIG = _descriptor.Descriptor(
  name='ContextScoringFunctionConfig',
  full_name='mobvoi.ContextScoringFunctionConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='app_context', full_name='mobvoi.ContextScoringFunctionConfig.app_context', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='query_context', full_name='mobvoi.ContextScoringFunctionConfig.query_context', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='class_context', full_name='mobvoi.ContextScoringFunctionConfig.class_context', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=344,
)


_APPCONTEXTSCORINGFUNCTIONCONFIG = _descriptor.Descriptor(
  name='AppContextScoringFunctionConfig',
  full_name='mobvoi.AppContextScoringFunctionConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='length_linear', full_name='mobvoi.AppContextScoringFunctionConfig.length_linear', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='alpha', full_name='mobvoi.AppContextScoringFunctionConfig.alpha', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0.9),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='beta', full_name='mobvoi.AppContextScoringFunctionConfig.beta', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='p1', full_name='mobvoi.AppContextScoringFunctionConfig.p1', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='p2', full_name='mobvoi.AppContextScoringFunctionConfig.p2', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(-1.5),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='full_match', full_name='mobvoi.AppContextScoringFunctionConfig.full_match', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='length_pow', full_name='mobvoi.AppContextScoringFunctionConfig.length_pow', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='min_length', full_name='mobvoi.AppContextScoringFunctionConfig.min_length', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=347,
  serialized_end=552,
)


_QUERYCONTEXTSCORINGFUNCTIONCONFIG = _descriptor.Descriptor(
  name='QueryContextScoringFunctionConfig',
  full_name='mobvoi.QueryContextScoringFunctionConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='length_linear', full_name='mobvoi.QueryContextScoringFunctionConfig.length_linear', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='alpha', full_name='mobvoi.QueryContextScoringFunctionConfig.alpha', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0.8),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='beta', full_name='mobvoi.QueryContextScoringFunctionConfig.beta', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='p1', full_name='mobvoi.QueryContextScoringFunctionConfig.p1', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(-1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='p2', full_name='mobvoi.QueryContextScoringFunctionConfig.p2', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(-2),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='full_match', full_name='mobvoi.QueryContextScoringFunctionConfig.full_match', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='length_pow', full_name='mobvoi.QueryContextScoringFunctionConfig.length_pow', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='min_length', full_name='mobvoi.QueryContextScoringFunctionConfig.min_length', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=555,
  serialized_end=762,
)


_BASESCORINGFUNCTIONCONFIG = _descriptor.Descriptor(
  name='BaseScoringFunctionConfig',
  full_name='mobvoi.BaseScoringFunctionConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='weight', full_name='mobvoi.BaseScoringFunctionConfig.weight', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=764,
  serialized_end=807,
)


_LMRESCORERCONFIG = _descriptor.Descriptor(
  name='LMRescorerConfig',
  full_name='mobvoi.LMRescorerConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='model_type', full_name='mobvoi.LMRescorerConfig.model_type', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='kenlm_config', full_name='mobvoi.LMRescorerConfig.kenlm_config', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='homophone_path', full_name='mobvoi.LMRescorerConfig.homophone_path', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='function_config', full_name='mobvoi.LMRescorerConfig.function_config', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='base_score_config', full_name='mobvoi.LMRescorerConfig.base_score_config', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=810,
  serialized_end=1040,
)

_CONTEXTSCORINGFUNCTIONCONFIG.fields_by_name['app_context'].message_type = _APPCONTEXTSCORINGFUNCTIONCONFIG
_CONTEXTSCORINGFUNCTIONCONFIG.fields_by_name['query_context'].message_type = _QUERYCONTEXTSCORINGFUNCTIONCONFIG
_CONTEXTSCORINGFUNCTIONCONFIG.fields_by_name['class_context'].message_type = _QUERYCONTEXTSCORINGFUNCTIONCONFIG
_LMRESCORERCONFIG.fields_by_name['kenlm_config'].message_type = _KENLMCONFIG
_LMRESCORERCONFIG.fields_by_name['function_config'].message_type = _CONTEXTSCORINGFUNCTIONCONFIG
_LMRESCORERCONFIG.fields_by_name['base_score_config'].message_type = _BASESCORINGFUNCTIONCONFIG
DESCRIPTOR.message_types_by_name['KenLMConfig'] = _KENLMCONFIG
DESCRIPTOR.message_types_by_name['ContextScoringFunctionConfig'] = _CONTEXTSCORINGFUNCTIONCONFIG
DESCRIPTOR.message_types_by_name['AppContextScoringFunctionConfig'] = _APPCONTEXTSCORINGFUNCTIONCONFIG
DESCRIPTOR.message_types_by_name['QueryContextScoringFunctionConfig'] = _QUERYCONTEXTSCORINGFUNCTIONCONFIG
DESCRIPTOR.message_types_by_name['BaseScoringFunctionConfig'] = _BASESCORINGFUNCTIONCONFIG
DESCRIPTOR.message_types_by_name['LMRescorerConfig'] = _LMRESCORERCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

KenLMConfig = _reflection.GeneratedProtocolMessageType('KenLMConfig', (_message.Message,), {
  'DESCRIPTOR' : _KENLMCONFIG,
  '__module__' : 'lm_rescorer_config_pb2'
  # @@protoc_insertion_point(class_scope:mobvoi.KenLMConfig)
  })
_sym_db.RegisterMessage(KenLMConfig)

ContextScoringFunctionConfig = _reflection.GeneratedProtocolMessageType('ContextScoringFunctionConfig', (_message.Message,), {
  'DESCRIPTOR' : _CONTEXTSCORINGFUNCTIONCONFIG,
  '__module__' : 'lm_rescorer_config_pb2'
  # @@protoc_insertion_point(class_scope:mobvoi.ContextScoringFunctionConfig)
  })
_sym_db.RegisterMessage(ContextScoringFunctionConfig)

AppContextScoringFunctionConfig = _reflection.GeneratedProtocolMessageType('AppContextScoringFunctionConfig', (_message.Message,), {
  'DESCRIPTOR' : _APPCONTEXTSCORINGFUNCTIONCONFIG,
  '__module__' : 'lm_rescorer_config_pb2'
  # @@protoc_insertion_point(class_scope:mobvoi.AppContextScoringFunctionConfig)
  })
_sym_db.RegisterMessage(AppContextScoringFunctionConfig)

QueryContextScoringFunctionConfig = _reflection.GeneratedProtocolMessageType('QueryContextScoringFunctionConfig', (_message.Message,), {
  'DESCRIPTOR' : _QUERYCONTEXTSCORINGFUNCTIONCONFIG,
  '__module__' : 'lm_rescorer_config_pb2'
  # @@protoc_insertion_point(class_scope:mobvoi.QueryContextScoringFunctionConfig)
  })
_sym_db.RegisterMessage(QueryContextScoringFunctionConfig)

BaseScoringFunctionConfig = _reflection.GeneratedProtocolMessageType('BaseScoringFunctionConfig', (_message.Message,), {
  'DESCRIPTOR' : _BASESCORINGFUNCTIONCONFIG,
  '__module__' : 'lm_rescorer_config_pb2'
  # @@protoc_insertion_point(class_scope:mobvoi.BaseScoringFunctionConfig)
  })
_sym_db.RegisterMessage(BaseScoringFunctionConfig)

LMRescorerConfig = _reflection.GeneratedProtocolMessageType('LMRescorerConfig', (_message.Message,), {
  'DESCRIPTOR' : _LMRESCORERCONFIG,
  '__module__' : 'lm_rescorer_config_pb2'
  # @@protoc_insertion_point(class_scope:mobvoi.LMRescorerConfig)
  })
_sym_db.RegisterMessage(LMRescorerConfig)


# @@protoc_insertion_point(module_scope)
