# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: post_processor.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='post_processor.proto',
  package='mobvoi',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14post_processor.proto\x12\x06mobvoi\",\n\x11LUProcessorParams\x12\x17\n\x0f\x63\x61nonical_table\x18\x01 \x02(\t\"v\n\x1c\x43rfPunctuationPreditorParams\x12\x19\n\x11punctuation_model\x18\x01 \x02(\t\x12\x1e\n\x16punc_word_symbol_table\x18\x02 \x02(\t\x12\x1b\n\x13interrogative_words\x18\x03 \x02(\t\"5\n\x10LMRescorerParams\x12\x0e\n\x06lm_fst\x18\x01 \x02(\t\x12\x11\n\tphi_label\x18\x02 \x02(\x05\"/\n\x14TextNormalizerParams\x12\x17\n\x0fnormalizing_fst\x18\x01 \x02(\t\"c\n\x1bInverseTextNormalizerParams\x12\x10\n\x08rule_fst\x18\x01 \x01(\t\x12\x18\n\x10replacement_list\x18\x02 \x01(\t\x12\x18\n\x10replace_reg_file\x18\x03 \x01(\t\">\n\x11NoiseFilterParams\x12\x13\n\x0bnoise_model\x18\x01 \x02(\t\x12\x14\n\x0cmodel_params\x18\x02 \x02(\t\"\x8a\x01\n\x16\x41lbertPunctuatorParams\x12\x17\n\x0f\x62\x65rt_vocab_path\x18\x01 \x02(\t\x12\x1a\n\x12input_sequence_len\x18\x02 \x02(\x05\x12\x1d\n\x15punctuator_model_path\x18\x03 \x02(\t\x12\x1c\n\x14punctuator_crf_probs\x18\x04 \x02(\t\"\xe4\x03\n\x13PostProcessorConfig\x12\x12\n\nmodel_type\x18\x01 \x03(\t\x12\x35\n\x12noise_filter_param\x18\x02 \x01(\x0b\x32\x19.mobvoi.NoiseFilterParams\x12L\n\x1e\x63rf_punctuation_preditor_param\x18\x03 \x01(\x0b\x32$.mobvoi.CrfPunctuationPreditorParams\x12\x35\n\x12lu_processor_param\x18\x04 \x01(\x0b\x32\x19.mobvoi.LUProcessorParams\x12\x33\n\x11lm_rescorer_param\x18\x05 \x01(\x0b\x32\x18.mobvoi.LMRescorerParams\x12;\n\x15text_normalizer_param\x18\x06 \x01(\x0b\x32\x1c.mobvoi.TextNormalizerParams\x12J\n\x1dinverse_text_normalizer_param\x18\x07 \x01(\x0b\x32#.mobvoi.InverseTextNormalizerParams\x12?\n\x17\x61lbert_punctuator_param\x18\x08 \x01(\x0b\x32\x1e.mobvoi.AlbertPunctuatorParams'
)




_LUPROCESSORPARAMS = _descriptor.Descriptor(
  name='LUProcessorParams',
  full_name='mobvoi.LUProcessorParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='canonical_table', full_name='mobvoi.LUProcessorParams.canonical_table', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=76,
)


_CRFPUNCTUATIONPREDITORPARAMS = _descriptor.Descriptor(
  name='CrfPunctuationPreditorParams',
  full_name='mobvoi.CrfPunctuationPreditorParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='punctuation_model', full_name='mobvoi.CrfPunctuationPreditorParams.punctuation_model', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='punc_word_symbol_table', full_name='mobvoi.CrfPunctuationPreditorParams.punc_word_symbol_table', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='interrogative_words', full_name='mobvoi.CrfPunctuationPreditorParams.interrogative_words', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=196,
)


_LMRESCORERPARAMS = _descriptor.Descriptor(
  name='LMRescorerParams',
  full_name='mobvoi.LMRescorerParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='lm_fst', full_name='mobvoi.LMRescorerParams.lm_fst', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='phi_label', full_name='mobvoi.LMRescorerParams.phi_label', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=198,
  serialized_end=251,
)


_TEXTNORMALIZERPARAMS = _descriptor.Descriptor(
  name='TextNormalizerParams',
  full_name='mobvoi.TextNormalizerParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='normalizing_fst', full_name='mobvoi.TextNormalizerParams.normalizing_fst', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=253,
  serialized_end=300,
)


_INVERSETEXTNORMALIZERPARAMS = _descriptor.Descriptor(
  name='InverseTextNormalizerParams',
  full_name='mobvoi.InverseTextNormalizerParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='rule_fst', full_name='mobvoi.InverseTextNormalizerParams.rule_fst', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='replacement_list', full_name='mobvoi.InverseTextNormalizerParams.replacement_list', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='replace_reg_file', full_name='mobvoi.InverseTextNormalizerParams.replace_reg_file', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=302,
  serialized_end=401,
)


_NOISEFILTERPARAMS = _descriptor.Descriptor(
  name='NoiseFilterParams',
  full_name='mobvoi.NoiseFilterParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='noise_model', full_name='mobvoi.NoiseFilterParams.noise_model', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='model_params', full_name='mobvoi.NoiseFilterParams.model_params', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=403,
  serialized_end=465,
)


_ALBERTPUNCTUATORPARAMS = _descriptor.Descriptor(
  name='AlbertPunctuatorParams',
  full_name='mobvoi.AlbertPunctuatorParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='bert_vocab_path', full_name='mobvoi.AlbertPunctuatorParams.bert_vocab_path', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='input_sequence_len', full_name='mobvoi.AlbertPunctuatorParams.input_sequence_len', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='punctuator_model_path', full_name='mobvoi.AlbertPunctuatorParams.punctuator_model_path', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='punctuator_crf_probs', full_name='mobvoi.AlbertPunctuatorParams.punctuator_crf_probs', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=468,
  serialized_end=606,
)


_POSTPROCESSORCONFIG = _descriptor.Descriptor(
  name='PostProcessorConfig',
  full_name='mobvoi.PostProcessorConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='model_type', full_name='mobvoi.PostProcessorConfig.model_type', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='noise_filter_param', full_name='mobvoi.PostProcessorConfig.noise_filter_param', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='crf_punctuation_preditor_param', full_name='mobvoi.PostProcessorConfig.crf_punctuation_preditor_param', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lu_processor_param', full_name='mobvoi.PostProcessorConfig.lu_processor_param', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lm_rescorer_param', full_name='mobvoi.PostProcessorConfig.lm_rescorer_param', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='text_normalizer_param', full_name='mobvoi.PostProcessorConfig.text_normalizer_param', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='inverse_text_normalizer_param', full_name='mobvoi.PostProcessorConfig.inverse_text_normalizer_param', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='albert_punctuator_param', full_name='mobvoi.PostProcessorConfig.albert_punctuator_param', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=609,
  serialized_end=1093,
)

_POSTPROCESSORCONFIG.fields_by_name['noise_filter_param'].message_type = _NOISEFILTERPARAMS
_POSTPROCESSORCONFIG.fields_by_name['crf_punctuation_preditor_param'].message_type = _CRFPUNCTUATIONPREDITORPARAMS
_POSTPROCESSORCONFIG.fields_by_name['lu_processor_param'].message_type = _LUPROCESSORPARAMS
_POSTPROCESSORCONFIG.fields_by_name['lm_rescorer_param'].message_type = _LMRESCORERPARAMS
_POSTPROCESSORCONFIG.fields_by_name['text_normalizer_param'].message_type = _TEXTNORMALIZERPARAMS
_POSTPROCESSORCONFIG.fields_by_name['inverse_text_normalizer_param'].message_type = _INVERSETEXTNORMALIZERPARAMS
_POSTPROCESSORCONFIG.fields_by_name['albert_punctuator_param'].message_type = _ALBERTPUNCTUATORPARAMS
DESCRIPTOR.message_types_by_name['LUProcessorParams'] = _LUPROCESSORPARAMS
DESCRIPTOR.message_types_by_name['CrfPunctuationPreditorParams'] = _CRFPUNCTUATIONPREDITORPARAMS
DESCRIPTOR.message_types_by_name['LMRescorerParams'] = _LMRESCORERPARAMS
DESCRIPTOR.message_types_by_name['TextNormalizerParams'] = _TEXTNORMALIZERPARAMS
DESCRIPTOR.message_types_by_name['InverseTextNormalizerParams'] = _INVERSETEXTNORMALIZERPARAMS
DESCRIPTOR.message_types_by_name['NoiseFilterParams'] = _NOISEFILTERPARAMS
DESCRIPTOR.message_types_by_name['AlbertPunctuatorParams'] = _ALBERTPUNCTUATORPARAMS
DESCRIPTOR.message_types_by_name['PostProcessorConfig'] = _POSTPROCESSORCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LUProcessorParams = _reflection.GeneratedProtocolMessageType('LUProcessorParams', (_message.Message,), {
  'DESCRIPTOR' : _LUPROCESSORPARAMS,
  '__module__' : 'post_processor_pb2'
  # @@protoc_insertion_point(class_scope:mobvoi.LUProcessorParams)
  })
_sym_db.RegisterMessage(LUProcessorParams)

CrfPunctuationPreditorParams = _reflection.GeneratedProtocolMessageType('CrfPunctuationPreditorParams', (_message.Message,), {
  'DESCRIPTOR' : _CRFPUNCTUATIONPREDITORPARAMS,
  '__module__' : 'post_processor_pb2'
  # @@protoc_insertion_point(class_scope:mobvoi.CrfPunctuationPreditorParams)
  })
_sym_db.RegisterMessage(CrfPunctuationPreditorParams)

LMRescorerParams = _reflection.GeneratedProtocolMessageType('LMRescorerParams', (_message.Message,), {
  'DESCRIPTOR' : _LMRESCORERPARAMS,
  '__module__' : 'post_processor_pb2'
  # @@protoc_insertion_point(class_scope:mobvoi.LMRescorerParams)
  })
_sym_db.RegisterMessage(LMRescorerParams)

TextNormalizerParams = _reflection.GeneratedProtocolMessageType('TextNormalizerParams', (_message.Message,), {
  'DESCRIPTOR' : _TEXTNORMALIZERPARAMS,
  '__module__' : 'post_processor_pb2'
  # @@protoc_insertion_point(class_scope:mobvoi.TextNormalizerParams)
  })
_sym_db.RegisterMessage(TextNormalizerParams)

InverseTextNormalizerParams = _reflection.GeneratedProtocolMessageType('InverseTextNormalizerParams', (_message.Message,), {
  'DESCRIPTOR' : _INVERSETEXTNORMALIZERPARAMS,
  '__module__' : 'post_processor_pb2'
  # @@protoc_insertion_point(class_scope:mobvoi.InverseTextNormalizerParams)
  })
_sym_db.RegisterMessage(InverseTextNormalizerParams)

NoiseFilterParams = _reflection.GeneratedProtocolMessageType('NoiseFilterParams', (_message.Message,), {
  'DESCRIPTOR' : _NOISEFILTERPARAMS,
  '__module__' : 'post_processor_pb2'
  # @@protoc_insertion_point(class_scope:mobvoi.NoiseFilterParams)
  })
_sym_db.RegisterMessage(NoiseFilterParams)

AlbertPunctuatorParams = _reflection.GeneratedProtocolMessageType('AlbertPunctuatorParams', (_message.Message,), {
  'DESCRIPTOR' : _ALBERTPUNCTUATORPARAMS,
  '__module__' : 'post_processor_pb2'
  # @@protoc_insertion_point(class_scope:mobvoi.AlbertPunctuatorParams)
  })
_sym_db.RegisterMessage(AlbertPunctuatorParams)

PostProcessorConfig = _reflection.GeneratedProtocolMessageType('PostProcessorConfig', (_message.Message,), {
  'DESCRIPTOR' : _POSTPROCESSORCONFIG,
  '__module__' : 'post_processor_pb2'
  # @@protoc_insertion_point(class_scope:mobvoi.PostProcessorConfig)
  })
_sym_db.RegisterMessage(PostProcessorConfig)


# @@protoc_insertion_point(module_scope)
